qsub sub/ur_fall/split_ae/rgb_depth/A0_B0_AB30_label_AB_test_A.pbs
qsub sub/ur_fall/split_ae/rgb_depth/A0_B0_AB30_label_AB_test_B.pbs
qsub sub/ur_fall/split_ae/rgb_depth/A0_B0_AB30_label_A_test_B.pbs
qsub sub/ur_fall/split_ae/rgb_depth/A0_B0_AB30_label_B_test_A.pbs
qsub sub/ur_fall/split_ae/rgb_depth/A0_B10_AB30_label_A_test_B.pbs
qsub sub/ur_fall/split_ae/rgb_depth/A0_B10_AB30_label_B_test_A.pbs
qsub sub/ur_fall/split_ae/rgb_depth/A0_B30_AB0_label_B_test_B.pbs
qsub sub/ur_fall/split_ae/rgb_depth/A10_B0_AB30_label_A_test_B.pbs
qsub sub/ur_fall/split_ae/rgb_depth/A10_B0_AB30_label_B_test_A.pbs
qsub sub/ur_fall/split_ae/rgb_depth/A10_B10_AB30_label_A_test_B.pbs
qsub sub/ur_fall/split_ae/rgb_depth/A10_B10_AB30_label_B_test_A.pbs
qsub sub/ur_fall/split_ae/rgb_depth/A30_B0_AB0_label_A_test_A.pbs